### ISSUE TITLE
Case Senstivity in Username Lookup

### ISSUE THREAD

**Issue by mubashariqbal** [madglory/nowplayus#101]
Some twitter users have mixed case letters in their Username and rails is not matching on them so the user profile page fails.

We either need to make the links to the user profile all lower case, or make the lookup case insensitive (I'd prefer this).

**Comment by erkattak** [comment]
This is due to Postgres' case sensitivity. We could either rewrite the finder method, or force lowercase on the username at all times.

**Comment by blainsmith** [comment]
This happens in MongoDB as well. It actually messes with sorting case-sensitive strings. Typically you end up having a `display_name` column that is for display only and a `name` column that is all lower for sorting and searching.

**Comment by erkattak** [comment]
If it's what @mubashariqbal mentioned w/ URLs then there's probably a solution out there for using friendly_id with Postgres

**Comment by mubashariqbal** [comment]
Can we just lower the string before doing the slug lookup?

**Comment by erkattak** [comment]
Yup. Got a fix coming
