### ISSUE TITLE
Mobile Responsive Cleanup

### ISSUE THREAD

**Issue by sethlouey** [madglory/nowplayus#119]
![image 6](https://f.cloud.github.com/assets/1234464/213823/ec7ff53c-83bd-11e2-8a11-6a0a7bc66391.png)
![image 5](https://f.cloud.github.com/assets/1234464/213824/ec7eb9c4-83bd-11e2-9762-afbe2e5bdc56.png)
![image 4](https://f.cloud.github.com/assets/1234464/213825/ec830920-83bd-11e2-890f-c6de4140d904.png)
![image 2](https://f.cloud.github.com/assets/1234464/213826/ec81a968-83bd-11e2-8d0a-da472cbb5e60.png)
![image](https://f.cloud.github.com/assets/1234464/213827/ec86310e-83bd-11e2-9b24-c7b6b984eacc.png)

**Comment by blainsmith** [comment]
This includes #121
