### ISSUE TITLE
iPad responsive cleanup

### ISSUE THREAD

**Issue by sethlouey** [madglory/nowplayus#121]
![photo 3](https://f.cloud.github.com/assets/1234464/213836/2719e2ba-83bf-11e2-883c-7730a1ef053e.PNG)
![photo 2](https://f.cloud.github.com/assets/1234464/213837/271cba12-83bf-11e2-918d-e2dec30dcfdd.PNG)
![photo 4](https://f.cloud.github.com/assets/1234464/213838/271fa88a-83bf-11e2-9ed6-98882898d4ed.PNG)
![photo 1](https://f.cloud.github.com/assets/1234464/213839/27229f86-83bf-11e2-9e9f-edd9a4a5ffd0.PNG)
![photo 5](https://f.cloud.github.com/assets/1234464/213840/2720f96a-83bf-11e2-8b0f-40135a7ef058.PNG)

We need to sit down tomorrow and hash these out together.

**Comment by blainsmith** [comment]
Closing since all responsive issues are covered in #119
