### ISSUE TITLE
Link profile platforms and games to external sources

### ISSUE THREAD

**Issue by blainsmith** [madglory/nowplayus#151]
Perhaps we can link each platform account to the public profile for each one.
- XBOX: https://live.xbox.com/en-US/Profile?GamerTag=blaindsmith
- PSN: http://us.playstation.com/publictrophy/index.htm?onlinename=blaindsmith
- STEAM: http://steamcommunity.com/id/blaindsmith

We can even link the games over to the public Giant Bomb pages.
- http://www.giantbomb.com/halo-4/3030-35533/

**Comment by sethlouey** [comment]
I do like that idea, but one thing that i was thinking about is, do we really want traffic to jump off our site or scrape that info to our site?! Just a question really...

**Comment by erkattak** [comment]
Makes sense for the platform stuff, but I'd want to keep them on our site for the games since we have the info.
