### ISSUE TITLE
Profiles need to update twitter avatar when changed

### ISSUE THREAD

**Issue by blainsmith** [madglory/nowplayus#152]
To keep updated avatars we could grab them whenever a user re-auths.

**Comment by erkattak** [comment]
This info is returned whenever someone logs in, we would just need to add a line to update user right where we are updating auths in the sessions_controller.rb

**Comment by blainsmith** [comment]
Cool, I figured the info was available without looking at the code. I'll take a stab at this.

**Comment by erkattak** [comment]
I just did it locally like an hour ago. Sorry for not tagging this

**Comment by blainsmith** [comment]
No prob. Trying to bit off bits and pieces of rails todos to get into it more. I only just assigned myself so I'll work on doing that sooner than later.
