### ISSUE TITLE
Friend lists

### ISSUE THREAD

**Issue by blainsmith** [madglory/nowplayus#153]
A guy seth and I played with tonight loved NPU since he is out of room on his xbox friend list. I guess your limit is 100. Maybe we can incorporate friends lists and create/store them as Twitter lists. Even if we add FB later there are lists to add friends to as well. Could make scheduling AND inviting folks easier too.

**Comment by erkattak** [comment]
On the clans page we could list out people with a follow button next to them all so you could add them on twitter
