### ISSUE TITLE
Add some base Platforms

### ISSUE THREAD

**Issue by erkattak** [madglory/nowplayus#20]
We should add the base platforms like XBOX, PSN, Steam, EA, Apple ID.

Maybe for now we should keep the user from creating new platforms. If we do that, rather than a dropdown, we can make radio buttons that are actually the logo for the network each game is on and have b&w/color for unselected/selected.

**Comment by blainsmith** [comment]
+1 on that and perhaps 1 more for in-person game nights like Jace's? Could be cool to get real world games other than console.

**Comment by erkattak** [comment]
I added PS3 and PC to production

**Comment by svperfecta** [comment]
All set with this one!
