### ISSUE TITLE
Battle.net and PvP.net hashtags retain periods

### ISSUE THREAD

**Issue by blainsmith** [madglory/nowplayus#234]
Hashtags for Battle.net and PvP.net should remove the period since this breaks the hashtag. 

Note: Would this happen for game titles as well if they had periods? Need to update the RegEx.

**Comment by mubashariqbal** [comment]
Shouldn't happen for games titles, we use the slug (which shouldn't contain .) or a custom value on the game table.

**Comment by erkattak** [comment]
I've tweaked this behavior a bit for games in my branch. I can do the same for platforms.
