### ISSUE TITLE
User should be able to cancel (destroy) an event

### ISSUE THREAD

**Issue by erkattak** [madglory/nowplayus#3]
There is currently no way to cancel an event.

Keep in mind that on destroy, any Player records associated w/ the event must also be destroyed.

**Comment by mubashariqbal** [comment]
Would it be better to have some kind of soft-delete, that way you can see if an event you wanted to go to was canceled instead of just disappearing from the site?

Soft delete would stop it appearing on the homepage, and listing, but would still appear on your dashboard view

**Comment by erkattak** [comment]
Yes!

**Comment by erkattak** [comment]
Adding a deleted_at column and changing the destroy method to update this with a timestamp
