### ISSUE TITLE
HomeController# (ArgumentError) "wrong number of arguments (3 for 2)"

### ISSUE THREAD

**Issue by CL4P-TP** [madglory/nowplayus#36]
<table><tr><th>Exception</th><td>wrong number of arguments (3 for 2)</td></tr><tr><th>Last Occurrence</th><td>February 19, 2013 11:10:04 -0500</td></tr><tr><th>Count</th><td>1</td></tr></table>

## Stack Trace

<pre><a href='https://github.com/madgloryint/nowplayus/blob/95b844e2367511304b00d3851bacf4ef8f7545ba/app/models/event.rb#L33'>/Users/erik/Dropbox/Code/nowplayus/app/models/event.rb:33:in `future'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/95b844e2367511304b00d3851bacf4ef8f7545ba/app/controllers/home_controller.rb#L6'>/Users/erik/Dropbox/Code/nowplayus/app/controllers/home_controller.rb:6:in `index'</a>
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.11/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.11/lib/abstract_controller/base.rb:167:in `process_action'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.11/lib/action_controller/metal/rendering.rb:10:in `process_action'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.11/lib/abstract_controller/callbacks.rb:18:in `block in process_action'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/activesupport-3.2.11/lib/active_support/callbacks.rb:425:in `_run__3472699617376159547__process_action__4206439801760573365__callbacks'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/activesupport-3.2.11/lib/active_support/callbacks.rb:405:in `__run_callback'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/activesupport-3.2.11/lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/activesupport-3.2.11/lib/active_support/callbacks.rb:81:in `run_callbacks'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.11/lib/abstract_controller/callbacks.rb:17:in `process_action'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.11/lib/action_controller/metal/rescue.rb:29:in `process_action'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.11/lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/activesupport-3.2.11/lib/active_support/notifications.rb:123:in `block in instrument'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/activesupport-3.2.11/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/activesupport-3.2.11/lib/active_support/notifications.rb:123:in `instrument'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.11/lib/action_controller/metal/instrumentation.rb:29:in `process_action'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.11/lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/activerecord-3.2.11/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.11/lib/abstract_controller/base.rb:121:in `process'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.11/lib/abstract_controller/rendering.rb:45:in `process'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.11/lib/action_controller/metal.rb:203:in `dispatch'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.11/lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.11/lib/action_controller/metal.rb:246:in `block in action'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.11/lib/action_dispatch/routing/route_set.rb:73:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.11/lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.11/lib/action_dispatch/routing/route_set.rb:36:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/journey-1.0.4/lib/journey/router.rb:68:in `block in call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/journey-1.0.4/lib/journey/router.rb:56:in `each'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/journey-1.0.4/lib/journey/router.rb:56:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.11/lib/action_dispatch/routing/route_set.rb:601:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/sass-3.2.3/lib/sass/plugin/rack.rb:54:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.11/lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/rack-1.4.3/lib/rack/etag.rb:23:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/rack-1.4.3/lib/rack/conditionalget.rb:25:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.11/lib/action_dispatch/middleware/head.rb:14:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.11/lib/action_dispatch/middleware/params_parser.rb:21:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.11/lib/action_dispatch/middleware/flash.rb:242:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/rack-1.4.3/lib/rack/session/abstract/id.rb:210:in `context'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/rack-1.4.3/lib/rack/session/abstract/id.rb:205:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.11/lib/action_dispatch/middleware/cookies.rb:341:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/activerecord-3.2.11/lib/active_record/query_cache.rb:64:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/activerecord-3.2.11/lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.11/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/activesupport-3.2.11/lib/active_support/callbacks.rb:405:in `_run__1209749330214058113__call__3797159328742030130__callbacks'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/activesupport-3.2.11/lib/active_support/callbacks.rb:405:in `__run_callback'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/activesupport-3.2.11/lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/activesupport-3.2.11/lib/active_support/callbacks.rb:81:in `run_callbacks'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.11/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.11/lib/action_dispatch/middleware/reloader.rb:65:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.11/lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.11/lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.11/lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/railties-3.2.11/lib/rails/rack/logger.rb:32:in `call_app'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/railties-3.2.11/lib/rails/rack/logger.rb:16:in `block in call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/activesupport-3.2.11/lib/active_support/tagged_logging.rb:22:in `tagged'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/railties-3.2.11/lib/rails/rack/logger.rb:16:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.11/lib/action_dispatch/middleware/request_id.rb:22:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/rack-1.4.3/lib/rack/methodoverride.rb:21:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/rack-1.4.3/lib/rack/runtime.rb:17:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/activesupport-3.2.11/lib/active_support/cache/strategy/local_cache.rb:72:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/rack-1.4.3/lib/rack/lock.rb:15:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.11/lib/action_dispatch/middleware/static.rb:62:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/railties-3.2.11/lib/rails/engine.rb:479:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/railties-3.2.11/lib/rails/application.rb:223:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/rack-1.4.3/lib/rack/content_length.rb:14:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/railties-3.2.11/lib/rails/rack/log_tailer.rb:17:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/global/gems/puma-1.6.3/lib/puma/server.rb:412:in `handle_request'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/global/gems/puma-1.6.3/lib/puma/server.rb:306:in `process_client'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/global/gems/puma-1.6.3/lib/puma/server.rb:215:in `block in run'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/global/gems/puma-1.6.3/lib/puma/thread_pool.rb:94:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/global/gems/puma-1.6.3/lib/puma/thread_pool.rb:94:in `block in spawn_thread'</pre>

Fingerprint: `26038c1268e0f77ba4e0ee6334719084f7116ee1`

**Comment by CL4P-TP** [comment]
<table><tr><th>Occurred At</th><td>February 19, 2013 11:10:05 -0500</td></tr><tr><th>URL</th><td>[GET] /</td></tr><tr><th>Params</th><td><table><tr><th>controller</th><td>home</td></tr><tr><th>action</th><td>index</td></tr></table></td></tr><tr><th>Session</th><td><table><tr><th>user_id</th><td>8</td></tr><tr><th>session_id</th><td>fefbcc300b23b64b229b6dd0d1bdd8be</td></tr><tr><th>_csrf_token</th><td>XFIJSWZu8iIlU4B/NtlaTVicQLM0919FVDhp4hV09eA=</td></tr></table></td></tr><tr><th>IP Address</th><td>127.0.0.1</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.1</td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_2) AppleWebKit/537.17 (KHTML, like Gecko) Chrome/24.0.1312.57 Safari/537.17</td></tr><tr><th>Accept Encoding</th><td>gzip,deflate,sdch</td></tr><tr><th>Accept</th><td>text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8</td></tr></table></td></tr></table>

**Comment by erkattak** [comment]
Just fixing the error messages/issues so they make sense. Had to do some digging to find the right call in party_foul
