### ISSUE TITLE
When creating or joining an event, a user should be able to specify their gamertag 

### ISSUE THREAD

**Issue by erkattak** [madglory/nowplayus#4]

**Comment by erkattak** [comment]
For example, my gamertag on Xbox is brkattk, but my twitter handle is brickattack.

**Comment by mubashariqbal** [comment]
Should we make that part of a more global user profile? Probably don't need to set it on each event right?

**Comment by blainsmith** [comment]
Global profile gamer tags would be ideal, Xbox, PS, and Steam to cover the top 3?

**Comment by erkattak** [comment]
My idea was to eventually break out Platform as it's own object (that acts like a tag) and associate Gamertag as another sort of tag. That way the first time you join a game on a platform you hadn't previously used, it'll ask your gamertag. After that it'll just know its XXX for XBOX and YYY for PS3.

Thoughts?

**Comment by mubashariqbal** [comment]
So ultimately that gamer tag would be associated with the user right? So we can include in on their profile?

I like the idea of collecting it when the user makes the event, but think it needs to be associated directly with the user...

**Comment by erkattak** [comment]
It would be, but it's not necessarily the same for each platform. This way it also doesn't restrict which platforms can be used on NPU based on what fields we have on the User table

**Comment by erkattak** [comment]
Here's how I see it:

Platform
- name - string
- unique index on name

Event
- platform_id - integer

PlatformAccount
- user_id - integer
- platform_id - integer
- username - string
- unique index on platform_id user_id

**Comment by erkattak** [comment]
All thats left with this is the UI, which I'll get up tonight.

**Comment by erkattak** [comment]
Added the PlatformAccount area to a User's profile edit page (using nested_form rocks).

The only thing left is to display the username next to the player's avatar. For now we can just do 

``` ruby
= player.platform_username event.platform
```

since I added the #platform_username method to User. This does create n+1 query issues, and I was toying with eager loading the platform accounts, but can't seem to limit it to a single platform right now without causing craziness. If someone wants to take a stab later, it was something like this:

``` ruby
class Event
    has_many :players, through: :participants, foreign_key: :user_id, class_name: 'User', source: :user, order: 'created_at ASC', include: :platform_accounts #, conditions: ->(instance) { ['platform_accounts.platform_id = ?', instance.platform_id] }
  #...
end
```

So the include call was to eager load their platform accounts. You can add conditions to that via a proc like what's commented out at the end of the has_many line above, but I'm not entirely sure how to access the instance's platform_id or how you'd get that data that in a view without triggering yet another query.
[Association Basics - conditions](http://guides.rubyonrails.org/association_basics.html#has_many-conditions)

If the player doesn't have a PlatformAccount for the event's Platform, we should display a link to edit their profile saying "Want to add your #{event.platform_name} account?"

**Comment by erkattak** [comment]
Closing this for now, but if we get big, this will be a problem.
