### ISSUE TITLE
Player status column and Joining v Pending

### ISSUE THREAD

**Issue by erkattak** [madglory/nowplayus#5]
What is the intention here?

**Comment by mubashariqbal** [comment]
Since some games have a limit of how many people can play at the same time the idea was to allow people to "queue" to play if the slots are filled already. 

We can rename the states, but the idea was that you should be "on the team", or you could be "on the bench".

**Comment by erkattak** [comment]
I'm going to hit this up tonight.

**Comment by erkattak** [comment]
So I got rid of the status column. Basically how it'll work is you can always join, but the first X (slots #) of people to join will be "on the team" the rest will be "on the bench". Simpler than handling state and managing #'s columns
