### ISSUE TITLE
Mobile button issues

### ISSUE THREAD

**Issue by sethlouey** [madglory/nowplayus#56]
Create event button and update user form buttons have weird styling conflicts via mobile.

**Comment by blainsmith** [comment]
- [ ] Tweet button is also extremely large which is why I left it as a regular link when no one is listed in the Joining column.
- [ ] Join button on column blows out past the bottom border

**Comment by sethlouey** [comment]
Agreed that twitter in content form doesn't need to be a button. That way there isn't two twitter buttons on a page. The join button makes more sense in the left column under the back button. (Mubs and I discussed this last night

**Comment by blainsmith** [comment]
Sounds like a plan. I will tackle this issue and the avatars.

**Comment by erkattak** [comment]
I question the need for a back button at all. Maybe make it say 'Events' or 'Home' rather than 'Back' (think if they're coming from the link that gets tweeted).

Also, I wouldn't put the tweet button under it if we're trying to get people to do that before going 'back'

**Comment by sethlouey** [comment]
Mubs and I agree. We changed it last night to go to the host profile, but changing the wording to events and linking to your personal event listing seems more reasonable at this point.
