### ISSUE TITLE
Tweet Game hashtags

### ISSUE THREAD

**Issue by sethlouey** [madglory/nowplayus#58]
I feel that the game title should also be a hashtag in the tweet. That way when searching game titles on twitter, people will see NPU and it expands the broad range of viewers.

**Comment by erkattak** [comment]
I'm going to start working on the lightboxed twitter forms today, so we can add this to the default.

It'll depend on how the event's title is written.. We can strip spaces and non-letters, so "Black Ops 2" would be #BlackOps2 and "Call of Duty: Black Ops 2" would be #CallOfDutyBlackOps2. It could get lengthy, but I guess it's only a suggestion at this point

**Comment by sethlouey** [comment]
Awesome!

**Comment by blainsmith** [comment]
Another option for game hashtags is we could ask for the hashtag on event creation as another field? The hashtag field could have an auto-suggest of previously entered ones from the db.

This would make tweeting faster instead of having to possibly edit the tweet text.

**Comment by svperfecta** [comment]
+1
