### ISSUE TITLE
Player Slot needs to add in host

### ISSUE THREAD

**Issue by sethlouey** [madglory/nowplayus#59]
Host is excluded from the slot count.

**Comment by blainsmith** [comment]
Should we override `players.count` to always return the count + 1?

```
def slots_filled
    players.count >= slots ? slots : players.count
end
```

However...

Seth, you also mentioned displaying all people who joined and pending to show whether the event is overloaded. (Ex. 6/4)

**Comment by erkattak** [comment]
I think we should change slots to :total_players, so the form would say "How many total players?"

Then we add a :is_host boolean to the Participant table.

Then we also add the host as a Participant with the :is_host flag when they create an event.

It'll get rid of a lot of the logic and extra queries around players. I can work this all out pretty quickly, too.

**Comment by erkattak** [comment]
That would also make it so when you did players.count  on event it would be the correct number of people.

**Comment by sethlouey** [comment]
Agreed that it should show total players. That way a user can quickly see if there are too many friends playing one game which in turn will let them create a new schedule. Host still should be included in this count.

**Comment by blainsmith** [comment]
@brickattack Cool. I was looking around to see if the host was included in the participant table. This makes more sense to add them in with a flag. Less logic.

**Comment by erkattak** [comment]
Less LoD (Law of Demeter or Legion of Doom)
