### ISSUE TITLE
After event reporting

### ISSUE THREAD

**Issue by sethlouey** [madglory/nowplayus#61]
Would be cool to have stats of hosting accomplishments, joined games, etc on the player profile page. X joined games, X hosted games, X accomplishments. 

Just a thought...

**Comment by mubashariqbal** [comment]
good idea!

**Comment by sethlouey** [comment]
Cool! I didn't realize that you can add milestones to it.

**Comment by erkattak** [comment]
I agree, but how would we add these?

**Comment by svperfecta** [comment]
Not a fan of this one for now.. I think we should focus on scheduling.  Reporting is _really_ difficult and is asking a lot of the players.  Just my 0.02.

**Comment by svperfecta** [comment]
We're doing it :)
