### ISSUE TITLE
nowplayus text on homepage contains spaces

### ISSUE THREAD

**Issue by blainsmith** [madglory/nowplayus#62]
Since stripping the `<span class"highlight">` from the HAML and using proper HAML there is now a space between the nowplayus words. Need to stop HAML from placing a space by doing.

```
now
%span.highlight play
us
```

**Comment by blainsmith** [comment]
I can't find a HAML workaround for this issue with out putting the `<span>` tag right in the file.

**Comment by erkattak** [comment]
Go w/ the way it was for now.

HAML is opinionated and I guess, technically, this is incorrect markup w/o the spaces. Maybe not?
