### ISSUE TITLE
Profile Edit Style Issues

### ISSUE THREAD

**Issue by sethlouey** [madglory/nowplayus#63]
- View profile button needs to have font color of #2d9478. 
- There also needs to be some padding between the buttons. 
- Mobile version should stack.
- Time Zone dropdown spreads off screen via mobile.
- Platform Accounts field's padding is not lined up with the rest of the forms.

![Screen Shot 2013-02-20 at 12 18 10 PM](https://f.cloud.github.com/assets/1234464/176848/b60f705c-7b81-11e2-85b0-a21ff41e5e1f.png)
![Screen Shot 2013-02-20 at 12 17 58 PM](https://f.cloud.github.com/assets/1234464/176849/b9c56a3a-7b81-11e2-8cf4-095ebc7adc70.png)
![Screen Shot 2013-02-20 at 12 22 21 PM](https://f.cloud.github.com/assets/1234464/176862/20735e90-7b82-11e2-8f57-864a4818482d.png)

**Comment by blainsmith** [comment]
I think the platform username should stay indented since it is a child of the Platform field. The rest makes sense.

**Comment by sethlouey** [comment]
It's so minimal that it doesn't make sense. IMHO

**Comment by blainsmith** [comment]
Perhaps it needs better treatment then. Especially if someone will end up having multiple platform accounts. Ideally it should be:

Platform:
[ XBOX ] - [ blaindsmith ]
[ PSN ] - [ blaindsmith ]

With the dropdown and inputs next to each other.

**Comment by sethlouey** [comment]
There is also an underline on Platform title.
