### ISSUE TITLE
All events created aren't located in link

### ISSUE THREAD

**Issue by sethlouey** [madglory/nowplayus#68]
My events link should show all events participated in. Currently it is displaying joined events only

**Comment by erkattak** [comment]
The code I pushed earlier should take care of anything created from this point on. Any older events wouldn't have the host as a participant. Basically, whenever you create an event now, it also adds you as a participant (with a flag for host).

So the nowplay.us/users/you/events should show all future events you're participating in, whether you made them or joined them.

**Comment by mubashariqbal** [comment]
There's only a few events, is there a way to fix these thru the console easily?

**Comment by erkattak** [comment]
:+1:  in there now

**Comment by erkattak** [comment]
@sethlouey check it now. should be working

**Comment by sethlouey** [comment]
@brickattack yup, they are in there. Cool thanks
