### ISSUE TITLE
Can't save profile form after adding then removing all platform accounts

### ISSUE THREAD

**Issue by blainsmith** [madglory/nowplayus#78]
"If I add more than 1 platform account and then remove them (leaving them blank), I can't submit the profile form." @jackmcdade

**Comment by erkattak** [comment]
So it turns out that simple_form adds the html5 attribute required="required" to inputs that are required. When nested_form removes them, it does not remove this attribute. When you click submit, the console says:

```
An invalid form control with name='user[platform_accounts_attributes][1363805515302][username]' is not focusable.
```

I'll be searching for a fix

**Comment by erkattak** [comment]
https://github.com/ryanb/nested_form/pull/89
