### ISSUE TITLE
TweetsController# (Twitter::Error::Forbidden) "Status is a duplicate"

### ISSUE THREAD

**Issue by CL4P-TP** [madglory/nowplayus#81]
<table><tr><th>Exception</th><td>Status is a duplicate</td></tr><tr><th>Last Occurrence</th><td>February 21, 2013 14:17:45 -0500</td></tr><tr><th>Count</th><td>1</td></tr></table>

## Stack Trace

<pre>/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/twitter-4.5.0/lib/twitter/response/raise_error.rb:21:in `on_complete'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/faraday-0.8.4/lib/faraday/response.rb:9:in `block in call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/faraday-0.8.4/lib/faraday/response.rb:63:in `on_complete'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/faraday-0.8.4/lib/faraday/response.rb:8:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/faraday-0.8.4/lib/faraday/request/url_encoded.rb:14:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/faraday-0.8.4/lib/faraday/request/multipart.rb:13:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/twitter-4.5.0/lib/twitter/request/multipart_with_file.rb:14:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/faraday-0.8.4/lib/faraday/connection.rb:226:in `run_request'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/faraday-0.8.4/lib/faraday/connection.rb:99:in `post'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/twitter-4.5.0/lib/twitter/client.rb:81:in `request'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/twitter-4.5.0/lib/twitter/client.rb:70:in `post'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/twitter-4.5.0/lib/twitter/api/utils.rb:82:in `object_from_response'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/twitter-4.5.0/lib/twitter/api/tweets.rb:129:in `update'
<a href='https://github.com/madgloryint/nowplayus/blob/ee4a5fdb0acb6402f8346f85bd413ddabc841875/app/models/tweet_sender.rb#L17'>/Users/erik/Dropbox/Code/nowplayus/app/models/tweet_sender.rb:17:in `send!'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/ee4a5fdb0acb6402f8346f85bd413ddabc841875/app/models/tweet_sender.rb#L6'>/Users/erik/Dropbox/Code/nowplayus/app/models/tweet_sender.rb:6:in `send_tweet'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/ee4a5fdb0acb6402f8346f85bd413ddabc841875/app/controllers/tweets_controller.rb#L13'>/Users/erik/Dropbox/Code/nowplayus/app/controllers/tweets_controller.rb:13:in `create'</a>
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.11/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.11/lib/abstract_controller/base.rb:167:in `process_action'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.11/lib/action_controller/metal/rendering.rb:10:in `process_action'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.11/lib/abstract_controller/callbacks.rb:18:in `block in process_action'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/activesupport-3.2.11/lib/active_support/callbacks.rb:447:in `_run__3450895798176875983__process_action__2642733658285208423__callbacks'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/activesupport-3.2.11/lib/active_support/callbacks.rb:405:in `__run_callback'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/activesupport-3.2.11/lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/activesupport-3.2.11/lib/active_support/callbacks.rb:81:in `run_callbacks'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.11/lib/abstract_controller/callbacks.rb:17:in `process_action'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.11/lib/action_controller/metal/rescue.rb:29:in `process_action'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.11/lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/activesupport-3.2.11/lib/active_support/notifications.rb:123:in `block in instrument'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/activesupport-3.2.11/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/activesupport-3.2.11/lib/active_support/notifications.rb:123:in `instrument'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.11/lib/action_controller/metal/instrumentation.rb:29:in `process_action'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.11/lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/activerecord-3.2.11/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.11/lib/abstract_controller/base.rb:121:in `process'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.11/lib/abstract_controller/rendering.rb:45:in `process'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.11/lib/action_controller/metal.rb:203:in `dispatch'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.11/lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.11/lib/action_controller/metal.rb:246:in `block in action'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.11/lib/action_dispatch/routing/route_set.rb:73:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.11/lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.11/lib/action_dispatch/routing/route_set.rb:36:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/journey-1.0.4/lib/journey/router.rb:68:in `block in call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/journey-1.0.4/lib/journey/router.rb:56:in `each'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/journey-1.0.4/lib/journey/router.rb:56:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.11/lib/action_dispatch/routing/route_set.rb:601:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/omniauth-1.1.3/lib/omniauth/strategy.rb:177:in `call!'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/omniauth-1.1.3/lib/omniauth/strategy.rb:157:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/omniauth-1.1.3/lib/omniauth/strategy.rb:177:in `call!'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/omniauth-1.1.3/lib/omniauth/strategy.rb:157:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/omniauth-1.1.3/lib/omniauth/builder.rb:48:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/sass-3.2.3/lib/sass/plugin/rack.rb:54:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.11/lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/rack-1.4.3/lib/rack/etag.rb:23:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/rack-1.4.3/lib/rack/conditionalget.rb:35:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.11/lib/action_dispatch/middleware/head.rb:14:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.11/lib/action_dispatch/middleware/params_parser.rb:21:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.11/lib/action_dispatch/middleware/flash.rb:242:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/rack-1.4.3/lib/rack/session/abstract/id.rb:210:in `context'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/rack-1.4.3/lib/rack/session/abstract/id.rb:205:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.11/lib/action_dispatch/middleware/cookies.rb:341:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/activerecord-3.2.11/lib/active_record/query_cache.rb:64:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/activerecord-3.2.11/lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.11/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/activesupport-3.2.11/lib/active_support/callbacks.rb:405:in `_run__2795717822414104761__call__3307215948529422108__callbacks'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/activesupport-3.2.11/lib/active_support/callbacks.rb:405:in `__run_callback'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/activesupport-3.2.11/lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/activesupport-3.2.11/lib/active_support/callbacks.rb:81:in `run_callbacks'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.11/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.11/lib/action_dispatch/middleware/reloader.rb:65:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.11/lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.11/lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.11/lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/railties-3.2.11/lib/rails/rack/logger.rb:32:in `call_app'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/railties-3.2.11/lib/rails/rack/logger.rb:16:in `block in call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/activesupport-3.2.11/lib/active_support/tagged_logging.rb:22:in `tagged'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/railties-3.2.11/lib/rails/rack/logger.rb:16:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.11/lib/action_dispatch/middleware/request_id.rb:22:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/rack-1.4.3/lib/rack/methodoverride.rb:21:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/rack-1.4.3/lib/rack/runtime.rb:17:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/activesupport-3.2.11/lib/active_support/cache/strategy/local_cache.rb:72:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/rack-1.4.3/lib/rack/lock.rb:15:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.11/lib/action_dispatch/middleware/static.rb:62:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/railties-3.2.11/lib/rails/engine.rb:479:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/railties-3.2.11/lib/rails/application.rb:223:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/rack-1.4.3/lib/rack/content_length.rb:14:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/railties-3.2.11/lib/rails/rack/log_tailer.rb:17:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/global/gems/puma-1.6.3/lib/puma/server.rb:412:in `handle_request'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/global/gems/puma-1.6.3/lib/puma/server.rb:306:in `process_client'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/global/gems/puma-1.6.3/lib/puma/server.rb:215:in `block in run'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/global/gems/puma-1.6.3/lib/puma/thread_pool.rb:94:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/global/gems/puma-1.6.3/lib/puma/thread_pool.rb:94:in `block in spawn_thread'</pre>

Fingerprint: `f437c7d24e43cf2ad1c0c21df9a3fa752b8b7a3a`

**Comment by CL4P-TP** [comment]
<table><tr><th>Occurred At</th><td>February 21, 2013 14:17:46 -0500</td></tr><tr><th>URL</th><td>[POST] /events/1/tweets</td></tr><tr><th>Params</th><td><table><tr><th>action</th><td>create</td></tr><tr><th>controller</th><td>tweets</td></tr><tr><th>event_id</th><td>1</td></tr></table></td></tr><tr><th>Session</th><td><table><tr><th>user_id</th><td>10</td></tr><tr><th>session_id</th><td>e9b5935d7a9a4c53b50a95f9cf267bdb</td></tr><tr><th>_csrf_token</th><td>g6yHdzJxq0ZM7PyXnayxIL5A7/I4EZmlXK/rXppcC68=</td></tr><tr><th>flash</th><td>#<ActionDispatch::Flash::FlashHash:0x007fcc944641b0></td></tr></table></td></tr><tr><th>IP Address</th><td>127.0.0.1</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.1</td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_2) AppleWebKit/537.17 (KHTML, like Gecko) Chrome/24.0.1312.57 Safari/537.17</td></tr><tr><th>Accept Encoding</th><td>gzip,deflate,sdch</td></tr><tr><th>Accept</th><td>text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8</td></tr></table></td></tr></table>

**Comment by erkattak** [comment]
Disregard. This is from development on my machine.
