### ISSUE TITLE
Profile Game List

### ISSUE THREAD

**Issue by sethlouey** [madglory/nowplayus#83]
What do you think about an area where you can add game titles that you own on your profile page?

**Comment by erkattak** [comment]
I think Game should have it's own model before this feature. That way games are uniformly added to the system and you don't end up with Call of Duty BO2, CoD BO2, CoD Black Ops II, etc. It'd also be good when we go to add stats and stuff.

**Comment by erkattak** [comment]
Game Titles API for auto-completing game titles? http://dl.gamesradar.com/api/GamesRadar_Developer_API_Documentation.pdf

**Comment by erkattak** [comment]
http://www.giantbomb.com/api/documentation

**Comment by svperfecta** [comment]
Done!
