### ISSUE TITLE
Refactor Media Queries for all breakpoints

### ISSUE THREAD

**Issue by blainsmith** [madglory/nowplayus#90]
Right now the media queries are spread through each file. I plan to make put all of them into application.css.scss and implement all the right breakpoints.

http://css-tricks.com/snippets/css/media-queries-for-standard-devices/

This will fix issues #87 and #89 too.

**Comment by erkattak** [comment]
If you put them all into media_queries.css.scss it will be included by default

**Comment by blainsmith** [comment]
Cool. I will look through and also do the @import statements the SCSS way so they are rendered in the proper order.

**Comment by erkattak** [comment]
You're really looking for info about the rails asset pipeline and organization http://guides.rubyonrails.org/asset_pipeline.html#asset-organization

**Comment by blainsmith** [comment]
Sounds like the end result will be the following to ensure proper order.

```
/* ...
*= require unsemantic
*= require forms
*= require_self
*= require responsive
*/
```

**Comment by erkattak** [comment]
don't forget events or modal, unless you've combined them into application
