### ISSUE TITLE
Basic count stats in footer

### ISSUE THREAD

**Issue by blainsmith** [madglory/nowplayus#95]
Users: X
Played: Y
Scheduled: Z

Basic, simple, interesting stats. Dribbble does this in their footer.

![Screen Shot 2013-02-27 at 1 09 24 PM](https://f.cloud.github.com/assets/483829/202148/e438ff84-8108-11e2-92b9-7f56338f0312.png)

**Comment by mubashariqbal** [comment]
Yes, but not yet, we don't have high enough numbers :)

**Comment by blainsmith** [comment]
Yup, mostly a brain dump idea filed under enhancements so MVP 2 is perfect.

**Comment by sethlouey** [comment]
Definitely could be cool in the future!
