### ISSUE TITLE
Disqus Integration

### ISSUE THREAD

**Issue by sethlouey** [madglory/nowplayus#98]
Would it be wise to allow disqus integration on the event description?

**Comment by mubashariqbal** [comment]
I'd rather build our own commenting system, we have some experience in such things, i'd like to limit who can comment on events.

**Comment by sethlouey** [comment]
Yeah, that makes sense.

**Comment by erkattak** [comment]
limit how?

**Comment by mubashariqbal** [comment]
I want people to login before they can comment, and since they are logged in, I don't want them to log in again thru disqus.  Eventually we may want to limit commenting to people actually coming to events.

**Comment by erkattak** [comment]
Makes sense
