### ISSUE TITLE
iCal feed for each user

### ISSUE THREAD

**Issue by blainsmith** [madglory/nowplayus#99]
I looks like iOS recognizes and asks to import events when clicking on .ics links so we could set up a feed for each user. We can place the link in the user profile.

`http://www.nowplay.us/users/blainsmith/events.ics`

If we need to keep them more private then we can obfuscate or generate an ID for each.

`http://www.nowplay.us/users/blainsmith/events-f81d4fae-7dec-11d0-a765-00a0c91e6bf6.ics`

That link would include all events I am hosting AND participating in. This would give us the temporary solution for adding those events to a calendar and allow people to set their alerts.

**Comment by svperfecta** [comment]
All set.  Needs DI.
